# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
    # Commands to start on workspace startup
tasks:
  - before: sudo apt install mysql-server
  - name: Terminal
    command: >
      mysql -e "CREATE DATABASE iclip;";    

       
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview 
